#!/usr/sbin/nft -f

table inet host_public_ingress {
    chain input {
        type filter hook input priority filter; policy accept;

        iifname { __PUBLIC_INTERFACES__ } ct state established,related accept
        iifname { __PUBLIC_INTERFACES__ } ip protocol icmp accept
        iifname { __PUBLIC_INTERFACES__ } meta l4proto ipv6-icmp accept
        iifname { __PUBLIC_INTERFACES__ } udp sport 67 udp dport 68 accept
        iifname { __PUBLIC_INTERFACES__ } udp sport 547 udp dport 546 accept
        iifname { __PUBLIC_INTERFACES__ } tcp dport { __ALLOWED_TCP_PORTS__ } accept
        iifname { __PUBLIC_INTERFACES__ } drop
    }
}
